// Pinned upstream inputs.
//
//   node tools/upstream.mjs lock    resolve upstream.config.json against the GitHub tree at each pinned
//                                   commit and write upstream.lock.json (bytes, git blob SHA-1, SHA-256)
//   node tools/upstream.mjs fetch   download every locked file from raw.githubusercontent.com at its commit
//                                   into tools/.cache/upstream/<id>/ and verify bytes + both hashes
//
// Nothing downstream reads the network: build scripts read the cache, and refuse a file that does not
// match the lock. Changing a pin means editing the commit in upstream.config.json and re-running `lock`.

import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

const HERE = import.meta.dirname;
const CONFIG = path.join(HERE, 'upstream.config.json');
const LOCK = path.join(HERE, 'upstream.lock.json');
export const CACHE = path.join(HERE, '.cache', 'upstream');

const blobSha1 = (buf) => crypto.createHash('sha1').update(`blob ${buf.length}\0`).update(buf).digest('hex');
const sha256 = (buf) => crypto.createHash('sha256').update(buf).digest('hex');

async function get(url, { json = false } = {}) {
  for (let attempt = 1; ; attempt++) {
    const res = await fetch(url, { headers: { 'User-Agent': 'jumper-lab-upstream' } });
    if (res.ok) return json ? res.json() : Buffer.from(await res.arrayBuffer());
    if (attempt >= 3 || res.status === 404 || res.status === 403) throw new Error(`${res.status} ${res.statusText}: ${url}`);
    await new Promise((r) => setTimeout(r, 1000 * attempt));
  }
}

const rawUrl = (src, p) => `https://raw.githubusercontent.com/${src.repo}/${src.commit}/${p}`;

async function lock() {
  const config = JSON.parse(fs.readFileSync(CONFIG, 'utf8'));
  const out = { _note: 'Generated by `node tools/upstream.mjs lock`. Do not edit by hand.', retrieved: new Date().toISOString().slice(0, 10), sources: [] };
  for (const src of config.sources) {
    const tree = await get(`https://api.github.com/repos/${src.repo}/git/trees/${src.commit}?recursive=1`, { json: true });
    if (tree.truncated) throw new Error(`tree for ${src.repo}@${src.commit} is truncated`);
    const blobs = new Map(tree.tree.filter((e) => e.type === 'blob').map((e) => [e.path, e]));
    const files = [];
    for (const p of src.paths) {
      const matches = p.endsWith('/') ? [...blobs.keys()].filter((k) => k.startsWith(p)).sort() : [p];
      if (!matches.length || !matches.every((m) => blobs.has(m))) throw new Error(`${src.repo}@${src.commit}: no such path ${p}`);
      for (const m of matches) {
        const entry = blobs.get(m);
        const buf = await get(rawUrl(src, m));
        if (buf.length !== entry.size || blobSha1(buf) !== entry.sha) throw new Error(`${m}: download does not match the tree`);
        files.push({ path: m, bytes: entry.size, gitBlobSha1: entry.sha, sha256: sha256(buf) });
        process.stdout.write('.');
      }
    }
    process.stdout.write('\n');
    out.sources.push({ id: src.id, repo: src.repo, commit: src.commit, license: src.license, copyright: src.copyright, files });
    console.log(`${src.repo}@${src.commit.slice(0, 12)}: ${files.length} files, ${files.reduce((s, f) => s + f.bytes, 0).toLocaleString()} bytes`);
  }
  fs.writeFileSync(LOCK, JSON.stringify(out, null, 2) + '\n');
  console.log(`wrote ${path.relative(process.cwd(), LOCK)}`);
}

export function readLock() {
  return JSON.parse(fs.readFileSync(LOCK, 'utf8'));
}

/** Absolute path of a locked file in the cache, after checking it against the lock. */
export function cached(id, p) {
  const src = readLock().sources.find((s) => s.id === id);
  const f = src?.files.find((x) => x.path === p);
  if (!f) throw new Error(`${id}:${p} is not in upstream.lock.json`);
  const file = path.join(CACHE, id, p);
  if (!fs.existsSync(file)) throw new Error(`${file} missing: run \`npm run upstream:fetch\``);
  const buf = fs.readFileSync(file);
  if (buf.length !== f.bytes || sha256(buf) !== f.sha256) throw new Error(`${file} does not match the lock: re-run \`npm run upstream:fetch\``);
  return file;
}

async function fetchAll() {
  const lockfile = readLock();
  let downloaded = 0, kept = 0;
  for (const src of lockfile.sources) {
    const queue = [...src.files];
    const worker = async () => {
      for (let f = queue.shift(); f; f = queue.shift()) {
        const dst = path.join(CACHE, src.id, f.path);
        if (fs.existsSync(dst)) {
          const have = fs.readFileSync(dst);
          if (have.length === f.bytes && sha256(have) === f.sha256) { kept++; continue; }
        }
        const buf = await get(rawUrl(src, f.path));
        if (buf.length !== f.bytes || blobSha1(buf) !== f.gitBlobSha1 || sha256(buf) !== f.sha256) throw new Error(`${src.id}:${f.path} does not match the lock`);
        fs.mkdirSync(path.dirname(dst), { recursive: true });
        fs.writeFileSync(dst, buf);
        downloaded++;
      }
    };
    await Promise.all(Array.from({ length: 6 }, worker));
    console.log(`${src.repo}@${src.commit.slice(0, 12)}: ${src.files.length} files verified`);
  }
  console.log(`downloaded ${downloaded}, already cached ${kept} -> ${path.relative(process.cwd(), CACHE)}`);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const cmd = process.argv[2];
  if (cmd === 'lock') await lock();
  else if (cmd === 'fetch') await fetchAll();
  else {
    console.error('usage: node tools/upstream.mjs lock|fetch');
    process.exit(2);
  }
}
